version: '3.8'

services:
  bot_app:
    build: .
    container_name: crm_telegram_bot
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    command: python main.py
