name: Deploy Telegram Bot

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub (если нужно пушить образ)
      if: false  # Отключено по умолчанию
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and deploy with Docker Compose
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DB_PATH: data/crm_bot.db
      run: |
        # Останавливаем и удаляем старые контейнеры
        docker-compose down || true
        
        # Собираем и запускаем
        docker-compose up -d --build
        
        # Проверяем статус
        docker ps -a
        docker logs crm_telegram_bot --tail 50

    - name: Verify deployment
      run: |
        # Можно добавить проверку работоспособности
        echo "Deployment completed at $(date)"
